export const Constant= {
  // FOR Applicant List
   ApplicantId: "Applicant ID",
   FirstName: "First Name",
   MiddleName: "Middle Name",
   LastName: "Last Name",
   Email: "Email",
   Phone: "Phone",
   Address: "Address",
   IsActive:"IS Active",
   CurrentCompany:"Current Company" ,
   CurrentDesignation: "Current Designation",
   DateOfBirth: "Date of Birth",
   TotalExperience: "Total Experience",
   ApplicantDate: "Applicant Date",
   DetailedExperience: "Detailed Experience",
   CurrentCTC: "Current CTC",
   ExpectedCTC: "Expected CTC",
   NoticePeriod: "Notice Period",
   ReasonForChange: "Reason For Change",
   CurrentLocation: "Current Location",
   PreferedLocation: "PreferedLocation",
}
